# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aClass', models.CharField(help_text='Clase donde se encuentra la funcion de calibracion', max_length=128, verbose_name='Clase donde se encuentra la funcion de calibracion')),
                ('aMethod', models.CharField(help_text='Metodo de calibracion', max_length=128, verbose_name='Metodo de calibracion')),
            ],
        ),
        migrations.CreateModel(
            name='SubSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del subsistema', max_length=24, unique=True, verbose_name='Codigo del subsistema')),
                ('description', models.CharField(help_text='Decripcion del subsistema', max_length=100, unique=True, verbose_name='Decripcion del subsistema')),
            ],
        ),
        migrations.RemoveField(
            model_name='tmlyvar',
            name='value',
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='varType',
            field=models.IntegerField(choices=[(0, 'Integer'), (1, 'Float'), (2, 'String')], default=0, verbose_name='Tipo de dato, 0=Integer, 1=Float, 2=String'),
        ),
        migrations.AddField(
            model_name='tmlyvar',
            name='calFValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tmlyvar',
            name='calIValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tmlyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=24, unique=True, verbose_name='Valor como string de la variable de telemetria'),
        ),
        migrations.AddField(
            model_name='tmlyvar',
            name='rawValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calibration',
            name='subsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrations', to='GroundSegment.SubSystem'),
        ),
    ]
