# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nombre del Sitio')),
                ('lat', models.FloatField(help_text='[Dato en Grados Decimales]', unique=True, verbose_name='Latitud')),
                ('lon', models.FloatField(help_text='[Grados Decimales]', unique=True, verbose_name='Longitud')),
                ('h', models.FloatField(help_text='[metros]', unique=True, verbose_name='altura')),
            ],
        ),
    ]
