# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criticity',
            options={'verbose_name': 'Criticidad', 'verbose_name_plural': 'Criticidades'},
        ),
        migrations.AddField(
            model_name='alarm',
            name='satellite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='GroundSegment.Satellite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criticity',
            name='sound',
            field=models.FileField(upload_to='', verbose_name='/media'),
        ),
    ]
