# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_auto_20160904_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='dtArrival',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='state',
            field=models.IntegerField(),
        ),
    ]
