# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('stopTime', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Satellite')),
            ],
        ),
        migrations.RenameModel(
            old_name='Site',
            new_name='Sitio',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='satellite',
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.AddField(
            model_name='pasada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Sitio'),
        ),
    ]
