# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0003_auto_20160905_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Sitio')),
                ('latitude', models.FloatField(help_text='[Grados Decimales]', verbose_name='latitude')),
                ('longitude', models.FloatField(help_text='[Grados Decimales]', verbose_name='Longitud')),
                ('altitude', models.FloatField(help_text='[metros]', verbose_name='altura')),
            ],
        ),
    ]
