# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0003_tlmyvartype_calibrationmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='alarmType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVarType', to='GroundSegment.Alarm'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='calibrationMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tlmyVarTypes', to='GroundSegment.Calibration'),
        ),
    ]
