# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0004_auto_20161126_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastCalFValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastCalIValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastCalSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=24, verbose_name='Valor como string de la variable de telemetria'),
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastRawValue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tmlyvar',
            name='calSValue',
            field=models.CharField(default=None, help_text='Valor como string de la variable de telemetria', max_length=24, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
