# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0006_auto_20161126_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='code',
            field=models.CharField(db_index=True, help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del tipo de variable'),
        ),
    ]
