# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0007_alarmtypenotificationtype_contact_notification_notificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Sin mensaje')),
            ],
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='alarmType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.AlarmType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='notificationType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.NotificationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='no@no.com.ar', max_length=512, verbose_name='EMail del contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='alarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='GroundSegment.Alarm'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ntry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default='Sin mensaje'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='code',
            field=models.CharField(default='code', help_text='Codigo del tipo de notificacion', max_length=64, unique=True, verbose_name='Codigo del tipo de notificacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description',
            field=models.CharField(default='desc', help_text='Decripcion del tipo de notificacion', max_length=128, unique=True, verbose_name='Decripcion del tipo de Notificacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='messageTemplate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.MessageTemplate'),
            preserve_default=False,
        ),
    ]
