# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0008_auto_20160927_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='ntry',
            field=models.IntegerField(default=0),
        ),
    ]
