# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0009_auto_20160927_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='AlarmTypeNotificationTypes', to='GroundSegment.Contact'),
        ),
    ]
