# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0009_auto_20161126_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='alarmType',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVarType', to='GroundSegment.Alarm'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='calibrationMethod',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tlmyVarTypes', to='GroundSegment.Calibration'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='satellite',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVarType', to='GroundSegment.Satellite'),
        ),
    ]
