# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0010_alarmtypenotificationtype_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contacts',
            field=models.ManyToManyField(related_name='notifications', to='GroundSegment.Contact'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notificationType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='GroundSegment.NotificationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='subject default', help_text='Asunto de la notificacion', max_length=128, verbose_name='Asunto de la notificacion'),
        ),
    ]
