# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0011_auto_20160927_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmtypenotificationtype',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notificationType',
        ),
        migrations.AddField(
            model_name='alarmtypenotificationtype',
            name='contacts',
            field=models.ManyToManyField(related_name='alarmTypeNotificationType', to='GroundSegment.Contact'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(default='sin nombre', help_text='Nombre de la plantilla', max_length=64, unique=True, verbose_name='Nombre de la plantilla'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='subject',
            field=models.CharField(default='sin nombre', help_text='Asunto del mensaje', max_length=64, unique=True, verbose_name='Asunto del mensaje'),
        ),
        migrations.AddField(
            model_name='notification',
            name='alarmTypeNotificationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='GroundSegment.AlarmTypeNotificationType'),
        ),
    ]
