# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-28 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0011_auto_20161127_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmlyvar',
            name='tmlyVarType',
        ),
    ]
