# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0012_remove_tmlyvar_tmlyvartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmlyvar',
            name='code',
            field=models.CharField(default='NoDef', help_text='Codigo de la variable, se quita relacion con maestro', max_length=24, verbose_name='Codigo del tipo de variable'),
        ),
    ]
