# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0013_auto_20161027_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmlyVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TmlyVarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del satelite, ejemplo FS2017', max_length=24, unique=True, verbose_name='Codigo del tipo de variable')),
                ('description', models.CharField(help_text='Decripcion del satelite', max_length=100, unique=True, verbose_name='Decripcion del tipo de variable')),
                ('limitMaxValue', models.FloatField(default=1.7976931348623157e+308)),
                ('limitMinValue', models.FloatField(default=2.2250738585072014e-308)),
                ('maxValue', models.FloatField(default=0)),
                ('minValue', models.FloatField(default=0)),
                ('alarmType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVarType', to='GroundSegment.Alarm')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVarType', to='GroundSegment.Satellite')),
            ],
        ),
        migrations.AddField(
            model_name='tmlyvar',
            name='tmlyVarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmlyVars', to='GroundSegment.TmlyVarType'),
        ),
    ]
