# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0013_tmlyvar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='sessionwrite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
