# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0014_auto_20161027_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TmlyVarType',
            new_name='TlmyVarType',
        ),
    ]
