# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0014_tlmyvartype_sessionwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmlyvar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 29, 12, 18, 53, 465263, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
