# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0015_tmlyvar_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlmyvartype',
            name='lastUpdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 29, 12, 19, 34, 512786, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
