# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-29 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0016_tlmyvartype_lastupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvartype',
            name='sessionwrite',
        ),
    ]
