# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0019_auto_20161202_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='limitMaxValue',
            field=models.FloatField(default=1.7976931348623157e+308, verbose_name='Maximo'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='limitMinValue',
            field=models.FloatField(default=2.2250738585072014e-308, verbose_name='Minimo'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='maxValue',
            field=models.FloatField(default=0, verbose_name='Maximo valor tolerable'),
        ),
        migrations.AlterField(
            model_name='tlmyvartype',
            name='minValue',
            field=models.FloatField(default=0, verbose_name='Minimo valor tolerable'),
        ),
    ]
