# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0020_auto_20161202_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo', max_length=24, verbose_name='Codigo del tipo de log')),
                ('description', models.CharField(help_text='Decripcion del log', max_length=512, verbose_name='Decripcion log')),
                ('module', models.CharField(help_text='Modulo que genera el log', max_length=64, verbose_name='Modulo')),
                ('logType', models.IntegerField(choices=[(0, 'Information'), (1, 'Warning'), (2, 'Error')], default=0, verbose_name='Tipo de log')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
