# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0022_auto_20161202_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchdog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo', max_length=24, verbose_name='Codigo del watchdog')),
                ('description', models.TextField(help_text='Decripcion del watchdog', max_length=512, verbose_name='Decripcion watchdog')),
                ('module', models.CharField(help_text='Modulo que genera actualiza el watchdog', max_length=64, verbose_name='Modulo')),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('tolerance', models.FloatField(verbose_name='Tiempo de tolerancia')),
            ],
        ),
    ]
