# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0023_watchdog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del tipo de paquete', max_length=24, unique=True, verbose_name='Codigo del tipo de paquete')),
                ('description', models.CharField(help_text='Decripcion del tipo de paquete', max_length=100, verbose_name='Decripcion del tipo de paquete')),
            ],
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='bitsLen',
            field=models.IntegerField(default=0),
        ),
    ]
