# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0024_auto_20161204_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo del coeficiente', max_length=24, verbose_name='Codigo del coeficiente')),
                ('value', models.FloatField(default=0.0)),
                ('tlmyVarType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='GroundSegment.TlmyVarType')),
            ],
        ),
    ]
