# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0027_auto_20170115_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasada',
            name='name',
        ),
        migrations.AddField(
            model_name='pasada',
            name='tle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasadas', to='GroundSegment.Tle'),
        ),
    ]
