# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0028_auto_20170115_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasada',
            name='duration',
            field=models.FloatField(default=0.0, help_text='[minutos]', verbose_name='Duracion'),
        ),
    ]
