# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0029_pasada_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTime', models.DateTimeField(auto_now_add=True)),
                ('receive_dataTime', models.DateTimeField(auto_now_add=True)),
                ('snow', models.FloatField(default=0.0, help_text='Nieve_colchon')),
                ('Precipitation', models.FloatField(default=0.0, help_text='Precipitacion_Totalizador')),
                ('Temperature', models.FloatField(default=0.0, help_text='Temperatura [C]')),
                ('Humidity', models.FloatField(default=0.0, help_text='Humedad [%]')),
                ('Wind_dir', models.FloatField(default=0.0, help_text='Direccion del Viento [grados]')),
                ('Wind_speed', models.FloatField(default=0.0, help_text='Velocidad del viento [KPH]')),
                ('Bat_volts', models.FloatField(default=0.0, help_text='Tension de Bateria [volts]')),
                ('cm_data', models.FloatField(default=0.0, help_text='cm ???????')),
            ],
        ),
        migrations.CreateModel(
            name='DCPPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Codigo de la Plataforma', max_length=24, unique=True, verbose_name='Codigo de la Plataforma')),
            ],
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='dcp_plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcpdatas', to='GroundSegment.DCPPlatform'),
        ),
    ]
