# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0030_auto_20170125_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(help_text='id del tipo de paquete', unique=True, verbose_name='id del tipo de paquete')),
                ('description', models.CharField(help_text='Decripcion del tipo de paquete', max_length=100, verbose_name='Decripcion del tipo de paquete')),
            ],
        ),
    ]
