# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0034_auto_20170130_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownlinkFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameCommand', models.IntegerField(help_text='frame Command', verbose_name='frame Command')),
                ('frameLength', models.IntegerField(help_text='Dimension del frame', verbose_name='Dimension del frame')),
                ('dataRate', models.IntegerField(help_text='Tasa de transferencia', verbose_name='Tasa de transferencia')),
                ('modulationName', models.CharField(help_text='Nombre de la modulacion', max_length=24, verbose_name='Nombre de la modulacion')),
                ('rssi', models.FloatField(help_text='RSSI')),
                ('frequency', models.FloatField(help_text='Frecuencia')),
                ('packetLength', models.IntegerField(help_text='Dimension del paquete', verbose_name='Dimension del paquete')),
            ],
        ),
    ]
