# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0036_uhfrawdata_datalen'),
    ]

    operations = [
        migrations.AddField(
            model_name='downlinkframe',
            name='satellite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downloadlinkFrames', to='GroundSegment.Satellite'),
            preserve_default=False,
        ),
    ]
