# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0036_uhfrawdata_datalen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcpplatform',
            name='equipo_marca',
            field=models.CharField(max_length=24, null=True, verbose_name='Marca del Equipo'),
        ),
        migrations.AddField(
            model_name='dcpplatform',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dcpplatform', to='GroundSegment.Sitio'),
        ),
        migrations.AddField(
            model_name='dcpplatform',
            name='type',
            field=models.CharField(max_length=24, null=True, verbose_name='Tipo de Plataforma'),
        ),
        migrations.AlterField(
            model_name='dcpplatform',
            name='code',
            field=models.CharField(max_length=24, unique=True, verbose_name='Codigo de la Plataforma'),
        ),
    ]
