# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0037_auto_20170131_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcpplatform',
            old_name='equipo_marca',
            new_name='equip_marca',
        ),
        migrations.AddField(
            model_name='dcpplatform',
            name='equip_model',
            field=models.CharField(max_length=24, null=True, verbose_name='Modelo del Equipo'),
        ),
    ]
