# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0037_downlinkframe_satellite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Unidad de medida', max_length=10, unique=True, verbose_name='Unidad de medida')),
                ('description', models.CharField(help_text='Descripcion de Unidad de medida', max_length=124, verbose_name='Descripcion de Unidad de medida')),
            ],
        ),
        migrations.AddField(
            model_name='tlmyvartype',
            name='unitOfMeasurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tlmyVarTypes', to='GroundSegment.UnitOfMeasurement'),
        ),
    ]
