# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0038_auto_20170131_1731'),
        ('GroundSegment', '0038_auto_20170131_1736'),
    ]

    operations = [
    ]
