# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0039_auto_20170131_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downlinkframe',
            name='ax25Destination',
        ),
        migrations.RemoveField(
            model_name='downlinkframe',
            name='ax25Protocol',
        ),
        migrations.RemoveField(
            model_name='downlinkframe',
            name='ax25Source',
        ),
    ]
