# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0040_auto_20170131_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='downlinkframe',
            name='ax25Control',
            field=models.CharField(help_text='ax25 Control value', max_length=16, null=True, verbose_name='ax25 Control value'),
        ),
        migrations.AddField(
            model_name='downlinkframe',
            name='ax25Destination',
            field=models.CharField(help_text='ax25 destination value', max_length=16, null=True, verbose_name='ax25 destination value'),
        ),
        migrations.AddField(
            model_name='downlinkframe',
            name='ax25Protocol',
            field=models.CharField(help_text='ax25 Protocol value', max_length=16, null=True, verbose_name='ax25 Protocol value'),
        ),
        migrations.AddField(
            model_name='downlinkframe',
            name='ax25Source',
            field=models.CharField(help_text='ax25 Source value', max_length=16, null=True, verbose_name='ax25 Source value'),
        ),
    ]
