# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0039_merge'),
        ('GroundSegment', '0041_auto_20170131_2030'),
    ]

    operations = [
    ]
