# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-02 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0042_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='uhfrawdata',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Indica si el paquete raw fue procesado'),
        ),
    ]
