# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0043_uhfrawdata_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcpdata',
            name='Bat_volts',
        ),
        migrations.RemoveField(
            model_name='dcpdata',
            name='Temperature',
        ),
        migrations.RemoveField(
            model_name='dcpdata',
            name='Wind_dir',
        ),
        migrations.RemoveField(
            model_name='dcpdata',
            name='Wind_speed',
        ),
        migrations.RemoveField(
            model_name='dcpdata',
            name='cm_data',
        ),
        migrations.RemoveField(
            model_name='dcpdata',
            name='snow',
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='Atm_preasure',
            field=models.FloatField(default=0.0, help_text='Presion Atmosferica [%]'),
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='Temp_max',
            field=models.FloatField(default=0.0, help_text='Temperatura maxima [C]'),
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='Temp_media',
            field=models.FloatField(default=0.0, help_text='Temperatura media [C]'),
        ),
        migrations.AddField(
            model_name='dcpdata',
            name='Temp_min',
            field=models.FloatField(default=0.0, help_text='Temperatura minima [C]'),
        ),
        migrations.AlterField(
            model_name='dcpplatform',
            name='equip_marca',
            field=models.CharField(default='no conocido', max_length=24, null=True, verbose_name='Marca del Equipo'),
        ),
        migrations.AlterField(
            model_name='dcpplatform',
            name='equip_model',
            field=models.CharField(default='no conocido', max_length=24, null=True, verbose_name='Modelo del Equipo'),
        ),
    ]
