# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0044_auto_20170206_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Codigo del Pais')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nombre del Pais')),
                ('description', models.CharField(max_length=24, unique=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='Codigo del Estado')),
                ('name', models.CharField(max_length=24, verbose_name='Nombre del Estado')),
                ('description', models.CharField(max_length=24, verbose_name='Descripcion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='GroundSegment.Country')),
            ],
        ),
        migrations.AddField(
            model_name='sitio',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='GroundSegment.State'),
        ),
    ]
