# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0047_auto_20170207_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='epoch',
            field=models.DateTimeField(null=True, verbose_name='Epoca del TLE'),
        ),
    ]
