# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0048_tle_epoch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(verbose_name='Fecha que se toma en consideracion')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Satellite')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Sitio')),
                ('tle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passGenerations', to='GroundSegment.Tle')),
            ],
        ),
    ]
