# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0049_passgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasada',
            name='passGeneration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='GroundSegment.PassGeneration'),
            preserve_default=False,
        ),
    ]
