# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:13
from __future__ import unicode_literals

import GroundSegment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0051_auto_20170313_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='lat',
            field=models.FloatField(help_text='[Dato en Grados Decimales]', validators=[GroundSegment.validators.validate_lat], verbose_name='Latitud'),
        ),
    ]
