# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GroundSegment', '0052_auto_20170324_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sent', models.DateTimeField(null=True)),
                ('executed', models.DateTimeField(null=True)),
                ('retry', models.IntegerField(default=0)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PassScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('script', models.TextField(default='Poner inclusion de django aca', help_text='Codifique el scripts', max_length=5120)),
                ('applied', models.BooleanField(default=False)),
                ('apass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passScripts', to='GroundSegment.Pasada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passScripts', to=settings.AUTH_USER_MODEL)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passScripts', to='GroundSegment.Satellite')),
            ],
        ),
        migrations.AddField(
            model_name='commandtype',
            name='maxRetry',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='command',
            name='commandType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='GroundSegment.CommandType'),
        ),
        migrations.AddField(
            model_name='command',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='GroundSegment.Satellite'),
        ),
    ]
