# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0054_command_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Failed'), (3, 'Executed'), (4, 'Expirated')], default=0),
        ),
    ]
