# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0056_auto_20170327_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='executedAt',
            new_name='executeAt',
        ),
    ]
