# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0057_auto_20170327_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='inContact',
            field=models.BooleanField(default=False, verbose_name='Si el satelite esta con enlace activo'),
        ),
    ]
