# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0059_command_binarycmb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='binarycmb',
        ),
        migrations.AddField(
            model_name='command',
            name='binarycmd',
            field=models.BinaryField(null=True, verbose_name='Comando en formato binario listo para ser enviado por TCP/IP'),
        ),
    ]
