# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0062_uhfrawdata_processedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='commServerIP',
            field=models.CharField(default='127.0.0.1', help_text='IP servidor/cortex', max_length=24, verbose_name='IP servidor/cortex '),
        ),
        migrations.AddField(
            model_name='satellite',
            name='commServerPort',
            field=models.CharField(default='3210', help_text='Puerto servidor/cortex', max_length=24, verbose_name='Puerto servidor/cortex'),
        ),
    ]
