# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-29 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0063_auto_20170601_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TmlyVar',
            new_name='TlmyVar',
        ),
    ]
