# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0064_auto_20170729_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtypeparameter',
            name='commandType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='GroundSegment.CommandType'),
        ),
    ]
