# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-15 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0066_auto_20170815_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvar',
            name='tlmyVarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tlmyVars', to='GroundSegment.TlmyVarType'),
        ),
    ]
