# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-15 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0067_auto_20170815_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlmyvar',
            name='tlmyVarType',
        ),
    ]
