# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0069_tlmyvar_tlmyvartype'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtypeparameter',
            name='parameter',
            field=models.IntegerField(default=0),
        ),
    ]
