# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0070_commandtypeparameter_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandtypeparameter',
            old_name='parameter',
            new_name='position',
        ),
    ]
