# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0071_auto_20170816_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='GroundSegment.Command')),
            ],
        ),
    ]
