# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0072_commandparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtypeparameter',
            name='valueMax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commandtypeparameter',
            name='valueMin',
            field=models.FloatField(default=0.0),
        ),
    ]
