# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0074_auto_20170822_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandparameter',
            name='value',
            field=models.CharField(default='', max_length=5),
        ),
    ]
