# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-29 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundSegment', '0075_auto_20170822_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlmyvartype',
            name='lastCalSValue',
            field=models.CharField(default='No defined', help_text='Valor como string de la variable de telemetria', max_length=24, null=True, verbose_name='Valor como string de la variable de telemetria'),
        ),
    ]
